AppointmentScheduler/Controllers/AppointmentController.cs
using AppointmentScheduler.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Data.SqlClient;

namespace AppointmentScheduler.Controllers
{
	public class AppointmentController : Controller
	{
		public IActionResult Index()
		{
			return RedirectToAction("List");
		}

		// GET: Appointment/List
		public IActionResult List()
		{
			string? email = HttpContext.Session.GetString("email");
			if (email == null)
			{
				return RedirectToAction("Index", "Home");
			}
			List<AppointmentModel> appointments = new();
			SqlCommand cmd = new($"select * from appointments where userEmail='{email}'", Connection.conn);
			using (var reader = cmd.ExecuteReader())
			{
				while (reader.Read())
				{
					appointments.Add(new()
					{
						Id = reader.GetInt32(0),
						Name = reader.GetString(1),
						UserEmail = reader.GetString(2),
						FromDate = reader.GetDateTime(3),
						ToDate = reader.GetDateTime(4),
						ReminderTime = reader.GetDateTime(5),
					});
				}
			}
			return View(appointments);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		// GET: Appointment/List
		public IActionResult List(IFormCollection form)
		{
			string? email = HttpContext.Session.GetString("email");
			if (email == null)
			{
				return RedirectToAction("Index", "Home");
			}
			List<AppointmentModel> appointments = new();
			SqlCommand cmd = new($"select * from appointments where userEmail='{email}' and name like '%{form["searchTerm"]}%'", Connection.conn);
			using (var reader = cmd.ExecuteReader())
			{
				while (reader.Read())
				{
					appointments.Add(new()
					{
						Id = reader.GetInt32(0),
						Name = reader.GetString(1),
						UserEmail = reader.GetString(2),
						FromDate = reader.GetDateTime(3),
						ToDate = reader.GetDateTime(4),
						ReminderTime = reader.GetDateTime(5),
					});
				}
			}
			return View(appointments);
		}

		// GET: Appointment/New
		public IActionResult New()
		{
            string? email = HttpContext.Session.GetString("email");
            if (email == null)
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult New(AppointmentModel model)
		{
			string? email = HttpContext.Session.GetString("email");
			if (email == null)
			{
                return RedirectToAction("Index", "Home");
            }
            ModelState.Remove("Id");
			ModelState.Remove("UserEmail");
            if (ModelState.IsValid)
			{
				SqlCommand command = new("createAppointment", Connection.conn);
				command.CommandType = System.Data.CommandType.StoredProcedure;
				command.Parameters.AddWithValue("@name", model.Name);
				command.Parameters.AddWithValue("@userEmail", email);
				command.Parameters.AddWithValue("@fromDate", model.FromDate);
				command.Parameters.AddWithValue("@toDate", model.ToDate);
				command.Parameters.AddWithValue("@reminderTime", model.ReminderTime);
				command.ExecuteNonQuery();
				TempData["success"] = "Appointment added";
			}
			return View(model);
		}
	}
}

AppointmentScheduler/Views/Shared/_AdditionalMenu.cshtml
@if (Context.Session.Get("email") != null)
{
	<li class="nav-item">
		<a class="nav-link text-dark" asp-controller="Appointment" asp-action="List">Appointments</a>
	</li>
}

AppointmentScheduler/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Appointment Scheduler</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppointmentScheduler.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Appointment Scheduler</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <partial name="_AdditionalMenu"/>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AppointmentScheduler/Views/Shared/_MessagePartial.cshtml
@if (TempData.ContainsKey("error"))
{
        <div id="errorMessage" class="alert alert-danger">
        @TempData["error"]
            <button class="btn-close" onclick="document.getElementById('errorMessage').remove()"></button>
        </div>
        <br/>
    TempData.Remove("error");
}
@if (TempData.ContainsKey("success"))
{
    <div id="successMessage" class="alert alert-success">
        @TempData["success"]
        <button class="btn-close" onclick="document.getElementById('successMessage').remove()"></button>
    </div>
    <br />
    TempData.Remove("success");
}